### ISSUE TITLE
Add the ability to hide in plants 

### ISSUE THREAD

**Issue by Devf-2** [space-wizards/docs#254]
Add the ability to hide in plants (as in SS13). Adding these mechanics will significantly improve the perception of the game and will not take much time to develop.

**Comment by Errant-4** [comment]
Hide what? You can already put small items in them. Do you mean an entire mob should be able to disappear in them?

**Comment by Devf-2** [comment]
Hiding behind plants yourself

**Comment by lzk228** [comment]
issues is not for feature requests (most of the time)

**Comment by PJB3005** [comment]
This is not the place to post ideaguysing. https://forum.spacestation14.com/c/development/feature-requests/52
