### ISSUE TITLE
Expeditions generate no ores and dungeon

### ISSUE THREAD

**Issue by Agustron24** [space-wizards/docs#271]
Expedition planets like lava and others are bugged, making them not generate neither dungeon or ores.

This happens with more planet types but i cant remember wich

**Comment by Agustron24** [comment]
This may be cause of the lava or plasma ponds, but idk about it

**Comment by deltanedas** [comment]
that means an exception happened, this needs logs

**Comment by slarticodefast** [comment]
Hey, this is our repository for design docs. If this issue is still happening for you, please open a new one on the repository for the game itself:
https://github.com/space-wizards/space-station-14/issues
