### ISSUE TITLE
Address the TODO OOP criticism section

### ISSUE THREAD

**Issue by AlbertSnows** [space-wizards/docs#82]
In the ECS section we have "[TODO: finish this](https://docs.spacestation14.com/en/robust-toolbox/ecs.html#todo-finish-this)" which reflects on some challenges of implementing an OOP style code base for SS14. We should clean this section up at minimum and hopefully add additional details later.

**Comment by AlbertSnows** [comment]
I have already done this, just making an issue for it. I will  create a PR and reference this issue shortly.

**Comment by Jezithyr** [comment]
dupe of #15
