### ISSUE TITLE
Proposals are not appearing on the docs site

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/docs#89]

**Comment by moonheart08** [comment]
@VasilisThePikachu any proposals that don't appear are a result of the proposal author not adding it to the sidebar. Feel free to PR a fix (not sure how they got merged without a sidebar entry but oh well!)

**Comment by VasilisThePikachu** [comment]
well i just followed what all other proposals did, which was just adding it in the proposals folder. No one told me i had to put it on the sidebar

**Comment by deltanedas** [comment]
add link in SUMMARY.md to untroll it

**Comment by mirrorcult** [comment]
theyre all on sidebar now
